---
etcd_version: "3.5.19"
etcd_data_dir: "/var/lib/etcd"
etcd_name: "etcd-{{ ansible_hostname }}"
etcd_listen_peer_urls: "http://0.0.0.0:2380"
etcd_listen_client_urls: "http://0.0.0.0:2379"
etcd_advertise_initial_peer_url: "http://{{ ansible_facts['enp0s8']['ipv4']['address'] }}:2380"
etcd_advertise_client_urls: "http://{{ ansible_facts['enp0s8']['ipv4']['address'] }}:2379"
etcd_initial_cluster: "etcd-master=http://192.168.56.10:2380,etcd-slave=http://192.168.56.11:2380,etcd-manager=http://192.168.56.12:2380"